#name: CI
#on:
#  push:
#    branches: [ main, develop ]
#  pull_request:
#jobs:
#  build:
#    runs-on: [self-hosted, be]
#    steps:
#      - run: npm run build
name: CI
on: push
jobs:
  build:
    runs-on: [backend]
    steps:
      - name: Checkout code  # ← Step 표시 이름
        uses: actions/checkout@v4

      - name: build
        run: echo "demo-be build!"
  deploy:
    runs-on: [backend]
    needs: build
    steps:
      - run: echo "deploy!"